Time: 2025/09/17 15:57:12
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 618, in Set_OffsetDistFromFunction
    get_offset_and_cut_speed(line0_length, line1_length, Z_XY, Z_UV, Z_Mach, \
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 573, in get_offset_and_cut_speed
    offset_XY_Mech = offset_function(cutspeed_XY_Mech)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\interpolate\polyint.py", line 74, in __call__
    y = self._evaluate(x)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\interpolate\interpolate.py", line 659, in _evaluate
    below_bounds, above_bounds = self._check_bounds(x_new)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\interpolate\interpolate.py", line 688, in _check_bounds
    raise ValueError("A value in x_new is below the interpolation "
ValueError: A value in x_new is below the interpolation range.

Time: 2025/09/17 16:14:38
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 430, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 695, in SortLine
    self.set_selected_line(line_num_st)
AttributeError: 'dxf_file' object has no attribute 'set_selected_line'

Time: 2025/09/17 16:14:42
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 430, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 695, in SortLine
    self.set_selected_line(line_num_st)
AttributeError: 'dxf_file' object has no attribute 'set_selected_line'

Time: 2025/09/17 16:20:43
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 430, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 691, in SortLine
    self.set_selected_line(line_num_st)
AttributeError: 'dxf_file' object has no attribute 'set_selected_line'

Time: 2025/09/17 16:20:43
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 430, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 691, in SortLine
    self.set_selected_line(line_num_st)
AttributeError: 'dxf_file' object has no attribute 'set_selected_line'

Time: 2025/09/17 16:31:56
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 430, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 691, in SortLine
    self.set_selected_line(line_num_st)
AttributeError: 'dxf_file' object has no attribute 'set_selected_line'

Time: 2025/09/17 16:31:58
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 618, in Set_OffsetDistFromFunction
    get_offset_and_cut_speed(line0_length, line1_length, Z_XY, Z_UV, Z_Mach, \
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 573, in get_offset_and_cut_speed
    offset_XY_Mech = offset_function(cutspeed_XY_Mech)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\interpolate\polyint.py", line 74, in __call__
    y = self._evaluate(x)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\interpolate\interpolate.py", line 659, in _evaluate
    below_bounds, above_bounds = self._check_bounds(x_new)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\interpolate\interpolate.py", line 688, in _check_bounds
    raise ValueError("A value in x_new is below the interpolation "
ValueError: A value in x_new is below the interpolation range.

Time: 2025/09/17 16:32:07
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 618, in Set_OffsetDistFromFunction
    get_offset_and_cut_speed(line0_length, line1_length, Z_XY, Z_UV, Z_Mach, \
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 573, in get_offset_and_cut_speed
    offset_XY_Mech = offset_function(cutspeed_XY_Mech)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\interpolate\polyint.py", line 74, in __call__
    y = self._evaluate(x)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\interpolate\interpolate.py", line 659, in _evaluate
    below_bounds, above_bounds = self._check_bounds(x_new)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\interpolate\interpolate.py", line 688, in _check_bounds
    raise ValueError("A value in x_new is below the interpolation "
ValueError: A value in x_new is below the interpolation range.

Time: 2025/09/17 22:14:47
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 430, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 689, in SortLine
    self.line_num_list[i] = sum(new_line_num_list,[])[j]
IndexError: list index out of range

Time: 2025/09/17 22:15:33
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 430, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 692, in SortLine
    self.line_num_list[i] = sum(new_line_num_list,[])[j]
IndexError: list index out of range

Time: 2025/09/18 07:19:20
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 175, in load_offset_func
    offset_function_file = np.genfromtxt(file_path, delimiter = ",", skip_header = 1, dtype = str)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\npyio.py", line 1749, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\_datasource.py", line 195, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\_datasource.py", line 535, in open
    raise IOError("%s not found." % path)
OSError:  not found.

Time: 2025/09/18 07:44:35
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 995, in path_chk
    x_m_array, y_m_array, u_m_array, v_m_array = make_offset_path(x_array, y_array, u_array, v_array, Z_XY, Z_UV, Z_Mach)
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 556, in make_offset_path
    xu_mid = (x_array[i] + u_array[i])/ 2.0
IndexError: index 701 is out of bounds for axis 0 with size 701

Time: 2025/09/18 07:44:52
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 995, in path_chk
    x_m_array, y_m_array, u_m_array, v_m_array = make_offset_path(x_array, y_array, u_array, v_array, Z_XY, Z_UV, Z_Mach)
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 556, in make_offset_path
    xu_mid = (x_array[i] + u_array[i])/ 2.0
IndexError: index 498 is out of bounds for axis 0 with size 498

Time: 2025/09/18 08:14:01
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 995, in path_chk
    x_m_array, y_m_array, u_m_array, v_m_array = make_offset_path(x_array, y_array, u_array, v_array, Z_XY, Z_UV, Z_Mach)
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 556, in make_offset_path
    xu_mid = (x_array[i] + u_array[i])/ 2.0
IndexError: index 491 is out of bounds for axis 0 with size 491

Time: 2025/09/18 09:49:28
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 504, in Set_OffsetDist
    self_collision_list = dxf_obj.check_self_collision()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 758, in check_self_collision
    temp_line.remove_self_collision()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\line_object.py", line 186, in remove_self_collision
    print(len(x), len(temp_x))
NameError: name 'x' is not defined

Time: 2025/09/18 10:21:13
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 439, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 729, in SortLine
    self.table.table.selection_set('I001')
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1439, in selection_set
    self._selection("set", items)
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1434, in _selection
    self.tk.call(self._w, "selection", selop, items)
_tkinter.TclError: Item I001 not found

Time: 2025/09/18 10:21:20
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 439, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 729, in SortLine
    self.table.table.selection_set('I001')
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1439, in selection_set
    self._selection("set", items)
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1434, in _selection
    self.tk.call(self._w, "selection", selop, items)
_tkinter.TclError: Item I001 not found

Time: 2025/09/18 10:21:22
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 439, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 729, in SortLine
    self.table.table.selection_set('I001')
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1439, in selection_set
    self._selection("set", items)
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1434, in _selection
    self.tk.call(self._w, "selection", selop, items)
_tkinter.TclError: Item I001 not found

Time: 2025/09/18 10:22:03
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 439, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 729, in SortLine
    self.table.table.selection_set('I001')
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1439, in selection_set
    self._selection("set", items)
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1434, in _selection
    self.tk.call(self._w, "selection", selop, items)
_tkinter.TclError: Item I001 not found

Time: 2025/09/18 10:22:06
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 439, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 729, in SortLine
    self.table.table.selection_set('I001')
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1439, in selection_set
    self._selection("set", items)
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1434, in _selection
    self.tk.call(self._w, "selection", selop, items)
_tkinter.TclError: Item I001 not found

Time: 2025/09/18 10:22:08
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 439, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 729, in SortLine
    self.table.table.selection_set('I001')
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1439, in selection_set
    self._selection("set", items)
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1434, in _selection
    self.tk.call(self._w, "selection", selop, items)
_tkinter.TclError: Item I001 not found

Time: 2025/09/18 10:22:10
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 439, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 729, in SortLine
    self.table.table.selection_set('I001')
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1439, in selection_set
    self._selection("set", items)
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1434, in _selection
    self.tk.call(self._w, "selection", selop, items)
_tkinter.TclError: Item I001 not found

Time: 2025/09/18 10:22:14
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 439, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 729, in SortLine
    self.table.table.selection_set('I001')
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1439, in selection_set
    self._selection("set", items)
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1434, in _selection
    self.tk.call(self._w, "selection", selop, items)
_tkinter.TclError: Item I001 not found

Time: 2025/09/18 10:22:15
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 439, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 729, in SortLine
    self.table.table.selection_set('I001')
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1439, in selection_set
    self._selection("set", items)
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1434, in _selection
    self.tk.call(self._w, "selection", selop, items)
_tkinter.TclError: Item I001 not found

Time: 2025/09/18 10:22:17
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 439, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 729, in SortLine
    self.table.table.selection_set('I001')
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1439, in selection_set
    self._selection("set", items)
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1434, in _selection
    self.tk.call(self._w, "selection", selop, items)
_tkinter.TclError: Item I001 not found

Time: 2025/09/18 10:22:21
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 439, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 729, in SortLine
    self.table.table.selection_set('I001')
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1439, in selection_set
    self._selection("set", items)
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1434, in _selection
    self.tk.call(self._w, "selection", selop, items)
_tkinter.TclError: Item I001 not found

Time: 2025/09/18 10:22:26
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 439, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 729, in SortLine
    self.table.table.selection_set('I001')
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1439, in selection_set
    self._selection("set", items)
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1434, in _selection
    self.tk.call(self._w, "selection", selop, items)
_tkinter.TclError: Item I001 not found

Time: 2025/09/18 10:22:33
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 439, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 729, in SortLine
    self.table.table.selection_set('I001')
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1439, in selection_set
    self._selection("set", items)
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1434, in _selection
    self.tk.call(self._w, "selection", selop, items)
_tkinter.TclError: Item I001 not found

Time: 2025/09/18 10:22:41
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 439, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 729, in SortLine
    self.table.table.selection_set('I001')
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1439, in selection_set
    self._selection("set", items)
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1434, in _selection
    self.tk.call(self._w, "selection", selop, items)
_tkinter.TclError: Item I001 not found

Time: 2025/09/18 10:22:52
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 439, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 729, in SortLine
    self.table.table.selection_set('I001')
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1439, in selection_set
    self._selection("set", items)
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1434, in _selection
    self.tk.call(self._w, "selection", selop, items)
_tkinter.TclError: Item I001 not found

Time: 2025/09/18 10:23:22
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 439, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 729, in SortLine
    self.table.table.selection_set('I001')
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1439, in selection_set
    self._selection("set", items)
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1434, in _selection
    self.tk.call(self._w, "selection", selop, items)
_tkinter.TclError: Item I001 not found

Time: 2025/09/18 10:30:10
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 439, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 729, in SortLine
    item_num = num2item(line_num_st)
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\cam_generic_lib.py", line 170, in num2item
    item = "I%s"%(temp.zfill(3))
AttributeError: 'int' object has no attribute 'zfill'

Time: 2025/09/18 10:30:17
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 439, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 729, in SortLine
    item_num = num2item(line_num_st)
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\cam_generic_lib.py", line 170, in num2item
    item = "I%s"%(temp.zfill(3))
AttributeError: 'numpy.int32' object has no attribute 'zfill'

Time: 2025/09/18 10:30:56
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 439, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 729, in SortLine
    item_num = num2item(line_num_st)
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\cam_generic_lib.py", line 170, in num2item
    item = "I%s"%(temp.zfill(3))
AttributeError: 'int' object has no attribute 'zfill'

Time: 2025/09/18 10:31:03
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 439, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 729, in SortLine
    item_num = num2item(line_num_st)
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\cam_generic_lib.py", line 170, in num2item
    item = "I%s"%(temp.zfill(3))
AttributeError: 'int' object has no attribute 'zfill'

Time: 2025/09/18 10:31:05
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 439, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 729, in SortLine
    item_num = num2item(line_num_st)
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\cam_generic_lib.py", line 170, in num2item
    item = "I%s"%(temp.zfill(3))
AttributeError: 'int' object has no attribute 'zfill'

Time: 2025/09/18 10:37:34
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 439, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 730, in SortLine
    self.table.table.selection_set("I001")
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1439, in selection_set
    self._selection("set", items)
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1434, in _selection
    self.tk.call(self._w, "selection", selop, items)
_tkinter.TclError: Item I001 not found

Time: 2025/09/18 10:37:43
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 439, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 730, in SortLine
    self.table.table.selection_set("I001")
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1439, in selection_set
    self._selection("set", items)
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1434, in _selection
    self.tk.call(self._w, "selection", selop, items)
_tkinter.TclError: Item I001 not found

Time: 2025/09/18 10:37:57
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 439, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 730, in SortLine
    self.table.table.selection_set("I001")
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1439, in selection_set
    self._selection("set", items)
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1434, in _selection
    self.tk.call(self._w, "selection", selop, items)
_tkinter.TclError: Item I001 not found

Time: 2025/09/18 10:38:10
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 439, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 730, in SortLine
    self.table.table.selection_set("I001")
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1439, in selection_set
    self._selection("set", items)
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1434, in _selection
    self.tk.call(self._w, "selection", selop, items)
_tkinter.TclError: Item I001 not found

Time: 2025/09/18 10:38:25
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 439, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 730, in SortLine
    self.table.table.selection_set("I001")
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1439, in selection_set
    self._selection("set", items)
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1434, in _selection
    self.tk.call(self._w, "selection", selop, items)
_tkinter.TclError: Item I001 not found

Time: 2025/09/18 10:41:00
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 439, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 730, in SortLine
    self.table.table.selection_set("I001")
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1439, in selection_set
    self._selection("set", items)
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1434, in _selection
    self.tk.call(self._w, "selection", selop, items)
_tkinter.TclError: Item I001 not found

Time: 2025/09/18 10:41:12
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 439, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 730, in SortLine
    self.table.table.selection_set("I001")
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1439, in selection_set
    self._selection("set", items)
  File "C:\ProgramData\Anaconda3\lib\tkinter\ttk.py", line 1434, in _selection
    self.tk.call(self._w, "selection", selop, items)
_tkinter.TclError: Item I001 not found

