Time: 2025/09/17 15:57:12
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 618, in Set_OffsetDistFromFunction
    get_offset_and_cut_speed(line0_length, line1_length, Z_XY, Z_UV, Z_Mach, \
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 573, in get_offset_and_cut_speed
    offset_XY_Mech = offset_function(cutspeed_XY_Mech)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\interpolate\polyint.py", line 74, in __call__
    y = self._evaluate(x)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\interpolate\interpolate.py", line 659, in _evaluate
    below_bounds, above_bounds = self._check_bounds(x_new)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\interpolate\interpolate.py", line 688, in _check_bounds
    raise ValueError("A value in x_new is below the interpolation "
ValueError: A value in x_new is below the interpolation range.

Time: 2025/09/17 16:14:38
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 430, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 695, in SortLine
    self.set_selected_line(line_num_st)
AttributeError: 'dxf_file' object has no attribute 'set_selected_line'

Time: 2025/09/17 16:14:42
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 430, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 695, in SortLine
    self.set_selected_line(line_num_st)
AttributeError: 'dxf_file' object has no attribute 'set_selected_line'

Time: 2025/09/17 16:20:43
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 430, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 691, in SortLine
    self.set_selected_line(line_num_st)
AttributeError: 'dxf_file' object has no attribute 'set_selected_line'

Time: 2025/09/17 16:20:43
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 430, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 691, in SortLine
    self.set_selected_line(line_num_st)
AttributeError: 'dxf_file' object has no attribute 'set_selected_line'

Time: 2025/09/17 16:31:56
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 430, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 691, in SortLine
    self.set_selected_line(line_num_st)
AttributeError: 'dxf_file' object has no attribute 'set_selected_line'

Time: 2025/09/17 16:31:58
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 618, in Set_OffsetDistFromFunction
    get_offset_and_cut_speed(line0_length, line1_length, Z_XY, Z_UV, Z_Mach, \
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 573, in get_offset_and_cut_speed
    offset_XY_Mech = offset_function(cutspeed_XY_Mech)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\interpolate\polyint.py", line 74, in __call__
    y = self._evaluate(x)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\interpolate\interpolate.py", line 659, in _evaluate
    below_bounds, above_bounds = self._check_bounds(x_new)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\interpolate\interpolate.py", line 688, in _check_bounds
    raise ValueError("A value in x_new is below the interpolation "
ValueError: A value in x_new is below the interpolation range.

Time: 2025/09/17 16:32:07
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 618, in Set_OffsetDistFromFunction
    get_offset_and_cut_speed(line0_length, line1_length, Z_XY, Z_UV, Z_Mach, \
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 573, in get_offset_and_cut_speed
    offset_XY_Mech = offset_function(cutspeed_XY_Mech)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\interpolate\polyint.py", line 74, in __call__
    y = self._evaluate(x)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\interpolate\interpolate.py", line 659, in _evaluate
    below_bounds, above_bounds = self._check_bounds(x_new)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\interpolate\interpolate.py", line 688, in _check_bounds
    raise ValueError("A value in x_new is below the interpolation "
ValueError: A value in x_new is below the interpolation range.

Time: 2025/09/17 22:14:47
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 430, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 689, in SortLine
    self.line_num_list[i] = sum(new_line_num_list,[])[j]
IndexError: list index out of range

Time: 2025/09/17 22:15:33
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 430, in AutoLineSort
    ret = dxf_obj.SortLine()
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\dxf_file.py", line 692, in SortLine
    self.line_num_list[i] = sum(new_line_num_list,[])[j]
IndexError: list index out of range

Time: 2025/09/18 07:19:20
Traceback (most recent call last):
  File "C:\Users\hirar\Documents\Git\HW_CAM\src\HWCAM.py", line 175, in load_offset_func
    offset_function_file = np.genfromtxt(file_path, delimiter = ",", skip_header = 1, dtype = str)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\npyio.py", line 1749, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\_datasource.py", line 195, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\_datasource.py", line 535, in open
    raise IOError("%s not found." % path)
OSError:  not found.

